version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "06:00"
      timezone: "Asia/Kolkata"
    commit-message:
      prefix: "chore(dev): "
    labels:
      - "dependencies"

  - package-ecosystem: terraform
    directory: ./infra
    schedule:
      interval: "monthly"
      time: "06:00"
      timezone: "Asia/Kolkata"
    commit-message:
      prefix: "chore: "
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "monthly"
      time: "06:00"
      timezone: "Asia/Kolkata"
    commit-message:
      prefix: "chore: "
    labels:
      - dependencies
