changelog:
  categories:
    - title: Newly Added Features
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
    - title: Newly Added (or Updated) Dependencies
      labels:
        - dependencies
